"""Commit sobre pedidos

Revision ID: 609c5217d605
Revises: 0ac3b8652cff
Create Date: 2023-06-15 21:37:12.752475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609c5217d605'
down_revision = '0ac3b8652cff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
