"""Inicial

Revision ID: ac2fac619491
Revises: 
Create Date: 2023-06-06 23:38:01.992485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2fac619491'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'descricao')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('descricao', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
