"""Commit sobre pedidos

Revision ID: c3c1d5ed4cb4
Revises: 609c5217d605
Create Date: 2023-06-16 13:50:58.974544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c1d5ed4cb4'
down_revision = '609c5217d605'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.String(), nullable=True))
        batch_op.drop_column('observacao')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacao', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('observacoes')

    # ### end Alembic commands ###
